Lint/AssignmentInCondition:
  Exclude:
    - 'bin/spring'

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'app/controllers/tickets_controller.rb'
    - 'app/mailers/application_mailer.rb'
    - 'app/models/application_record.rb'
    - 'config/application.rb'

Style/FrozenStringLiteralComment:
  Enabled: false

